[package]
name = "cuc-cli"
version = "0.1.0"
edition = "2024"
description = "A CLI tool to generate clink argmatcher completions from the usage spec."
authors = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
categories = ["command-line-utilities"]

[[bin]]
name = "cuc"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.98"
base64 = "0.22.1"
clap = { version = "4.5.41", features = ["derive"] }
cuc-lib = { workspace = true }
clap_usage = "2.0.3"
kdl = "6.3.4"
tera = "1.20.0"
which = "8.0.0"
winsplit = "0.1.0"
